project:
  type: website
  output-dir: ./docs

website:
  site-url: https://nanoyan.github.io/quarto-babel-prototyp/
  title: "quarto-babel-prototyp-de"
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/nanoyan/quarto-babel-prototyp/
  repo-actions: [issue]
  navbar:
    logo: IQB-klein.png
    left: 
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
    right:
      - text: "English"
        href: ../en
      - text: "Deutsch"
        href: .. 
lang: de
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
