project:
  type: website
  output-dir: ./docs/en

website:
  site-url: https://nanoyan.github.io/quarto-babel/
  title: "quarto-babel-prototyp-de"
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/nanoyan/quarto-babel/
  repo-actions: [issue]
  navbar:
    logo: IQB-klein.png
    left: 
      - text: "Home"
        href: ../en/index.html
      - text: "About"
        href: ../en/about.html
    right:
      - text: "English"
        href: ../en
      - text: "Deutsch"
        href: ..
lang: en
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
